### ISSUE TITLE
Обсудить, как будет работать проект

### ISSUE THREAD

**Issue by st1gmat** [web-ds-demographic/demographic_analyzer#10]

**Comment by st1gmat** [comment]
В итоге:
by @Midiy 

По поводу архитектуры:

Мне кажется, тут можно выделить три глобальных блока:
1. Сбор и, возможно, хранение данных (бэк).
2. Обработка данных (DS).
3. Отображение данных, UI (веб).

Взаимодействие между вебом и бэк+DS в формате WebAPI (просто потому что с ним знаком), т.е. бэк предоставляет некоторый API (набор эндпоинтов), а веб вызывает нужные ему методы (шлёт запросы) в нужной последовательности и делает нужные ему вещи с ответами.

Бэк можно сделать в виде микросервисов - отдельно тот бэк, который бэк, и отдельно - тот, который DS. В итоге, наверно, бэк и веб всё равно красиво сделать Докер-контейнерами, объединёнными Docker Compose, а тогда не очень важно - два контейнера или три.
Но это только возможный вариант - надо обдумать и обсудить плюсы и минусы микросервисов/монолитного бэка/чего-нибудь ещё, если появятся другие варианты.

Концептуальная схема взаимодействия (для случая микросервисов, для монолитного бэка такая же, только бэк блоку DS не HTTP-запросы шлёт, а напрямую дёргает методы):
0. Бэк (возможно, с какой-то периодичностью) проходится по заранее заданному списку источников данных и запоминает, для каких территорий и за какие периоды он может получить данные.
00. (Возможно, это должно быть не здесь/не так - с математикой модели я пока детально не разбирался) Бэк предзапрашивает откуда-то какие-то данные в каком-то объёме, отправляет их DS-блоку, DS-блок на основании этих данных считает параметры модели (возможно - зоопарка моделей).
1. Веб запрашивает у бэка список доступных территорий и периоды, за которые существуют данные (+, возможно, список источников данных).
2. Пользователь через UI выбирает, для какой территории построить прогноз и на основании данных за какой период (+, возможно, из какого источника их брать).
3. Веб шлёт запрос бэку.
4. Бэк проверяет, есть ли эакэшированный готовый результат прогноза по подобному запросу.
4.1. Если есть - переходим к п. 11.
5. (Если прогноза нет) Бэк проверяет, есть ли закэшированные исходные данные, соответствующие запросу.
5.1. Если есть - переходим к п. 7.
6. (Если исходных данных нет) Бэк получает исходные данные по указанной территории за указанный период (возможно, из указанного источника) и кэширует их на будущее.
7. Бэк отправляет исходные данные в блок DS.
8. (Возможно, не нужно, см. п. 00) Блок DS на основе данных настраивает параметры модели.
9. Блок DS прогоняет данные через модель (возможно, модели) и возвращает прогноз (возможно, прогнозы) бэку.
10. Бэк кэширует прогноз(ы) на будущее.
11. Бэк возвращает прогноз(ы) вебу.
12. Веб отображает прогноз(ы) пользователю.
13. Пользователь может запросить выгрузку прогноза - тогда в зависимости от того, как мы всё реализуем:
ЛИБО
14. Веб делает из того, что отдал ему бэк, файл и выгружает его.
ЛИБО
14. Веб отправляет запрос на выгрузку бэку.
15. Бэк берёт закэшированный прогноз (если его вдруг почему-то нет - повторяет пп. 5-10), формирует файл, отдаёт вебу.
16. Веб отдаёт пользователю полученный от бэка файл.

**Comment by st1gmat** [comment]
Приблизительно, как я это вижу
![image](https://github.com/web-ds-demographic/demographic_analyzer/assets/97258310/cf3ad45b-0950-4789-b652-3442435f1e53)

**Comment by Midiy** [comment]
Нарисовал какую-то визуализацию схемы взаимодействия, описанной [выше](https://github.com/web-ds-demographic/demographic_analyzer/issues/10#issuecomment-1762744317): [просмотр](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=demographics.drawio#R7T1bc6s4mr8mVd0PJ4UECPGYxEn3VPVU9Z4zUzO7L1vEJomrHZMlnNv8%2BhU3WUgfRsYSl5ie6bTBWIC%2B%2B%2F3KvXv98Vsavb38PdnEuyvsbH5cuasrjHFAfPaf%2FMzP8gzysVeeeU63m%2Brc4cSX7X%2Fi6qRTnf263cTvjQuzJNll27fmyXWy38frrHEuStPke%2FOyp2TXvOtb9BwrJ76so5169l%2FbTfZSnUUkPHzxe7x9fqluTXFQfvEYrf96TpOv%2B%2Bp%2B%2B2Qfl9%2B8RvUy1Tu%2Bv0Sb5Ltwyr2%2Fcu%2FSJMnKT68%2F7uJdvq%2F1jpW%2Fe2j5lj9yGu8znR%2BQ3%2F9F%2Fut%2F3jfo7e3l6fPdl%2F%2BNv6w%2BuTUEvkW7r9VmVI%2Bb%2Fax3J95vbvJNZkfF%2B7m3L9nrjh0h9rF4%2BTi%2Fh8OO3rM0%2BYvvIUIhO%2Fe03e3ukl2SFqu5j07sxoRfK3xzT%2FL%2FsW%2FKJ4g3CtAO74r4DjKsjJPXOEt%2Fsku%2BH6DnV2%2F2IsCtPpfGuyjbfmsuH1VI9MyX43f4M9myG2OnwnhUw7TGd891mmu8J1%2FTdVz9TASKtJJHnK6lsih9jjNlKfZBePPDqQLqJ2AA35NjGKCA6qH4RwXu7c0dXbn5%2BWSfVXSOqIIYuLriIXrd7vI3%2Fz3efYuz7TpqIlfyFq23WX4BcThefIvTLP5xKmbUP%2FBQc8NdUh0LqIM4VETkQchpR5QGWE6HgXtJMPD8bhCEZFgIuOEcIBBaggDyQhUEHoJYKHbswYDOAQa2qABhV5cMPHsgIHMAgSkywF4TBNihABm4IAxkMW0OBngWMDBFBjIMUOhPAAZOcNEwIJA4GBgGDBHmAANbvAgUydxgHkoie3MAgS2JTHX1UosQwLOwDKwRAcXjMyLGDi8JBope6mibZ4E9eYwvGQSBpwsBbE8aX7SB7AUAHwLtY2RNFiDvoviQ4qnD%2Bp46EzDwgd1eOVch%2B4uumJ3IPt%2F6xd%2B74swDu%2FaX4vhBuKL8i4WrmVbrfGL%2F1peyv%2FfF36D4S8qLfu2G7AGCTcgyrc3zV03IYq83ZPNrQHzKV68er3D95xiwf75Nsix5Zefo4dznCjTCZX%2FET%2FkZ6nJkUTADwB9txUHbjjfhSvEBY7HCFA511A3PkARuRFR4xmjjx4EWPF%2BSdPsfdlW0q3ZbF8AHQJ4PCyU6AtAtxDldE95dH%2FAh5rC4L2gSFbBYCUSHlTNMzpEde6Tbx7QBMPJ%2FX5PidJJu4vTTugTQTXGv9JdPn8TzvxZYXf%2BCfXou%2FtugePY4WLjtTX%2BC9zfBUxhKrDw0hyC76DHe3fJIZ33nKhbYxh9MYFLQjUmBNf6vKjzf2CG6dvpDCmLNLZCaNGBoJ7dFELOlJlQjNVz5z7%2BJJFvS2i8CdYtk5p0hWC%2BGziBNyxqdEaQA9ByOvbBaIygAGTz2UEC17v9M4812nS2Q6oQU5BwAIWXEN6C6I3%2BLs1WURV%2BKjJf3BWCdAPN1ScuIOw3w4OfcFRVccaXLDyl%2BdAlgmzDLhG68%2BdomEJsDE8dCE7BQA1oLm9PW%2FaH0CJBsjGRHqM4fBqosjbb7Iv114XMaEIMCB%2FYYneqEWX3phhJZ0%2FjxCWBsUUyf1vNlbODmW%2FO6BLMI1Qtx4rP2WomQAVttMTgQzC0MYHSzIdsUjoUZ2eu5pSQa3WtIU7UX%2BeWC%2B9hm50LtTf9VeclI9Fiv4BzdAiUDAUhAQAiSYibUDuS1OEO8yn1RhY0CIbZURptcwVtyU32bX8xP%2BkJQqnSGUOHbM3yaJ%2Bgzg6ovHJu60b8rw8oMaFUnRwHaLlguUDyNiXEIdjEta1nUyJub1DAbqIfERkug3lrGEPIBcjsiTLQlx1k7A0oTcGfsISdUa5TzITEV4bZgKneCrBF9747gUfeb10syiNb%2B%2BTax5QguelRfthLkl5QjcSswyEB4gJVwO1%2F4oXgL9tdVYgfNt%2FsI7LODlo9Ry1HJaA9P6UUZNApTgBz4LezShAufzq20wexuQ0nd8G4byeqms1AFwtptVbukPBtbD%2FqkBlcMIJM%2Bl383giRYFZLDE4SKKwgeR5CCRFDCH6A4tDnV%2FZQYzHAOZRMKpOw4hkpfIJPbXt0FCoB050NO30qAKBUw5oFngtaglVJFPV1gb4Lw0XFUYD89xWQ9rF%2F6PNgqrRIA2EKu0sBeKjudRU2NNfMMjKS1sGF7Zgio9JXsM9%2BnKyj1Mv%2Fi03uxx7lfBNG3H1dtiZY3SDAeRE7Lc4DAnCEqEC7PGeLGhmhm3DQth3I1thfl01dLymh16JaCVFTi2YFN5KsYbT98ek6jzTY%2B2AvmuDaWubYPFO7aSwOEkQrOxL7xm3JbgqQI%2BbA2IUHsuBMzCZv2L%2F8cdvOSU4KO85bkUP0eGAK2WEYMOYJK6L6%2FRfuzGU1ImwglKoUc3W6FM9wL0qY%2Bsvcsn%2BzjMxGuDfyUEGg8HhJC2sGCL9PEF2%2FQ1HMYX1oy7E7VJGiLzPEEtFgJtkZpW%2FpmTYl5SxuobcXQ0qZdrTXDPXp4w484JVT1mAePbajHwmpD8y5%2FdN4VuE10JXAwaFDepeGdzNsw1h6BePeYfL8%2FnLgtTrAvRAYhbbyrwIdBznFubngVaRdI2P6mP%2F9dcZ7i4L%2Fzg%2BvAr49XP8RvVz%2Bro030%2FsJxJ%2F6xzf4tfC7X8Kujwwr5Qb1AuRndjSjZhhXp7zoGb9nPsZuHtOIRufY8GgahHyLqkqCuCq%2F9227%2BUgpeueg6DHBAQ4R84pG6P6t2wlT1NHL7SjlbxvWlZpq6jTD9OoWQB0W8a%2BKGh3%2Bay7Y0xbxJ0%2BincNlbfsF7%2B%2FMHcvdNVEmQA1WVSx5ozETLTQdqq2PQ9xEe0RlEkXDJ3opgdO6LHY2s2fG5rwYTxce5aG%2F%2BbZD9cprrZL%2FYcWfDfmXr2a%2BbVpzKfgOJkbPntMJwiVQ5jOpsLcsMVyPDwA6l3bmeu9KktD4aShttDUha3GPykUiLEMnR4PZUbAIqa%2F12VBkiVxniIQgLbB9v0txVq7eR4ssni%2Bk7ce2Ls3ne8nt0vx2uJdzEZUJP%2Fj62tRvqWrvY9%2BYiE0K5PEZOUdCVCciRa%2FgRtSIUQkmtI%2F4gQgErlPUbe5my1Hmb7D%2FH71932QctoTXq0YaSFYdNhGK0NAs2OaDq%2FJp8q2oCivk3MVNlxOMkizLheBPvYvGYEYF4uEvWf%2FHpOc2KA2SaJWNNltzqgLTPYhGisqLgXwee1%2BYH1Oa4ruTp8ym%2BpsHQ%2FsV6uI9la9dyBPtGjEiLCjFVFGKnPTFWKtAQ8yPFOhGecltGuvi3x5X1zqDpkEp5ISSo46gDsqYXlBo%2FoI6Rbe%2F4cfRSrUnQd66PcC2%2FujwffCj74MMJINt4PvgwdHQVUg0ffNBP2cGD%2BuC1HYVoNkYhcpQYYtDTVXhIzObhVMeOGz5UUsLJIIYhVHpmODkGVChEz2GPdBn9zN9FrWhh9Qioyh%2Ba1Y%2BW7HIBDr9TeHswG96OJN4ehj1ZeyhHahG1xNnlGUbN%2BKrOgw0iCTSmiYyf%2BtBbaTo%2FZ8Igaepnns0oPuu5zXwxRPpqXXLqQ1CvbDpAS0ahtDpGYbPOjmtVdfWU7BjCwjX3wpXHda7Fpu5WtJS8tgnY1HgWkdWzk4MnkHrDqfsjWdSh7KqXM2a0lS452YzWtTqm3fxSkTtjmYOwdqzS2cpgtevZlUeX07ECGlo8bOURoxO72AD6VpTcKTl8I95LozL6YjAGHDU%2BNMZADpF5qIbH3XFQKeWiGiI6eoMGjCG7fx4odyb%2FawmDL2iJJ%2BAadi0byWcFJnTCzws%2F1BDBchLyFBiiO5qtbLgGbAYlYLW%2B85FCFIoflD1Qc42%2BflAiP4ylCAXyBok9u4CxPBChmU30mL5Tqg7zd9NZKXfnQGfIkRsZBoTf%2FuRED59IVIs8T17MELkhtUuKNwS9eVBilclcDyyoRbyzX6FkVd03RW3LFRT8e0G3ai%2F2wrxTqzrtXVXQnGaH8XsNG%2BJeWY0IaiBuWBVLDVkuJ%2BRJQKP3CsPeLLr9CGgpF1NyImrJijbm%2BFsQWGhPVUea4XbYgyKwRjP48c2PueZE1TKwWxHyZtPyB1G5pkXuEaytBVEpPqdUsZlSgYgPP7JlDWgWzbU%2BSHuX2rH8kUjNU2JGiAGjbwWcgzRWs0VxXHmzTHLt4YXptqMQNatAKEQShyqpg5eW9hIHdONZrhNqL%2BGrjt1%2F%2Fk2F1i9NNdypZ4NUrvxfFbAtRfKyQ8PVHTNtYtLxsR4W07IDj5fG1iPXKobCmc5DM%2BR0xCzU9IycZF7q%2B0RGYX9zqrgZv7ss9j9Kf8MZ6L%2F67Q3n029H6S5L5K6E%2FWNblqpv5ALOWlbZVXv90dobnhLbmqsXx9cmLTSfcBaSfJHcYDu9aFkWPPJKJ9NWQ%2BoYoY%2FxvJwG6KOz2mx0AtHOqyjt81kQiFwi74d9CUQpsXQs1X4iKt3JH6QMwR%2BvlnM06TNc9SaPMWpodnQ21EUl%2F2Agk4Q%2BdckNjJClPAqZuIJBGuz6LdNqfSEEK6Us%2BIppf9c3Klx6EiRaZjZq1uYZjHbb5z07XDM8j1PJsK6uEYgyt3gZpe5uqp%2B9bjebgiV8f9lm8Ze3qCCN72n0dpV31qstdueq6rO3TfJffQoP%2Fqgk3cSp7K7MZ2run69KM706%2BkfyVq1UnbhNsix5bZ77I37Kmmc%2BV3jvdHrArgx4umQy8YEBRxSw6WUVzJxNX3sQpuTpAnG7d5OvI66qSXWVm6ovXo4zTSDLgcyiIHnY1E39phBkPlYtlXosBH37tTDzGDVWImQgtaJOr7CrVhCgRWiHWqGZQiZyR7%2B6ePIaxEGafzD9QdZZA5UWB9YfRosJXEITLn1bkcym08%2BkmbpxVyVZJhVZjJIR7SZ181F6sCPRB%2FWcazd0%2BD%2B9qUXRTM51W5qnllmkL3%2BQFMu6L%2FdHIh6E5K5sNPCvPXKYCyANZtGmHmW0aMfCpuwJJQTtDWNQtPcSMeMXchWPjdTYhn0mtV9Ic%2BaAWLIlFnEFS4oR6Nrx5VJCPAHfzmjRpyENivrz0AZF3VRTg%2BfPJviEXd%2B5ZmpR6LiBx0xd2sRph6lP1EVOmPPSwJM6xunyf8w0sGuCm29J7MR9sdLYAg8yZyaAYgHTJT3Uj%2FROGrOgT3vdFBXomzXz0bfCIKc92Tbh6XIOYqrw2coXe6kmUVM5ecMW5dFB5scHQDzDWFD4zOk4U3f1fthgcT79W5JkUGMtNKi7N8BjiYjLSwGvDb%2BPpKshXxmJ0zcHHBFZSwotZYGr%2Bpg%2FjFhon%2Fu3NFe8jB53SiXkFLorBlB13OTshA%2FReku%2FDD6YTQBQLgPKXZo9RYDilOVdvUy7YX25JTwapAA%2BGK%2Fk7vLGGRLtuof5EJvaNTrAPRtKukhuAoEtFT7gQHnoQerugqXuzqLvWZ%2B85lNWhOUeYHwq1Mk%2BLgXnkT8QddFBGrYGtoeFLlPGhzNLXMmMn0BSeHB6Zc2ZNQVLauyEvKWyj2b81NjgIiLZdrQJDRWcausds4mmKa2QlBQ9%2FYgZbobiJpgaW1PjxOljpp6jYDYxgUN3N7MJr4qSMsGEVwpEfgeyOM3G03r6dybaUymYz7wQpadSX%2FeOPF0zkAePGIumyf0z3EHaWtBZRC1m2zQm0B4SMp9otdJnDGGvpzBy5aoOD9spQMW%2B%2FMzOIAnjFIpUmBy5dmYe0zKR%2FDiNt1vWSpb4BEaS01l46j9IXEyftZdMYBas3ZeCWaHbNzOcKgOZkJ0u7FgOQjNxNAhrH60q7%2BLyPfRr8uZEap1ZGtq05qsjRmz18XDlOw1SgxFqOMWAOFHVjV1SNA6t5IWW8bS3jpHkfv0sv4Ac8P4s3cKVmwtBvd95tuVQ3d9DDafM%2BDAIbcEALAKEYXCMGZwJAw1rfXwYWKMDH5qFB8MgsAcDjeSzPJ731roD62S%2Fj9dZ9Fhf7py9Mwjqgw%2FujJxVaHBjAOtjBfa6uwPqj1dOc%2FKL37xeypLmE%2FfUkLVU%2Blz8sBGUdupDsQHkkdSI4gwGF9epq%2B4iTwOTTUYeZHKMTlQUHhNDNVT28dmnNRHG%2FXbd7FNWRQ3CQGNe3PgwsCbCqLYaocwJNAgDjRyM8WEQ1g6l2oL2bAAEOfqKnTWlwq1hPW2IWKMKXsqvAQRr4sF1dFKT9htm4BZ%2BGzUXrZleBsDLaUtcvNL0lhwVpz6wXfW5NN5F2fZbc%2FkTKhRlH5vnSmDQdVZ4RPZ7KEu1OCtMeRN4beUZQRnP6RjaLlX4ue01gl1Bk2nkSgqsxK8zbSHUNsAd1MJSt24pIiA7VxNFbJfTzM3xBgRZ3hZxxhHGxKmhtwVnOnHGw%2B7IOOO55wd%2F%2FaM407RqD6ncomVKhb7ytZV6MGYd7Sb0RaFzfyv4rmmD86VwjeRgmbV4GacCyG%2BAnT%2FTeLNdZy0%2FkOaOit1CsHDXB%2Fbz35joKdfaJvvP8fvXXe4R58%2FvnPjkvWfpVo9jYnhuG9So8Ni%2BcN4TvsXQjnYWkpRfiYkEoYCf%2FAJ03gs6Agjo4TmxeL68ngqSl2MpR3WqrCmO%2Bqz5cOOl7oXHvlMebL6MOgAKI0xo%2FJ6k9UEjPqCmLRa96Z7b4rC8FVBAbchYI7Vinr1Eb%2FnHyq%2FLYBqlXPzl27jOY7zbfQ7KAmDrZLeL3t63pRu4uOJlu9v8Ef1Mvmb1QvWRhCKb%2BCn6yiVJdRfXELDkaCJknBFIlCrTwwzCSsd1J0Lgc26jqTOfRagUx9%2B3r7toH%2F8eRxvp1G2y%2BXkFmXLb%2FUucbvPNz3gN0O5Q6PMo1gGlQrmPCvBNmrz9ow5qOzCJVzFZ9ob%2BLfs%2F2%2BG7PEztr3Kh5DNpwo%2BL7Km3JGVK1p49cbQtwB1H79n3%2BF3CFUTO8u5WtKOiUB2p0cQYi8qXjp%2BxQhj2utk22n3OgzL7553EWCH%2B2QzhHEORhG3v065M9GAcOd7DUD4NkwqciNP7b3GJGsgwcFsSvUVVGmLWx6BZrXbY49OXi3bsnfdRxiiTSS8rpQeeq%2BMaXdDmJLT5IcFYgDv3%2FZhBI63lhkAjD3IxLeJqquIKah81sLzy8MJ4%2BkLX6%2FaNf1R55UHd8Ba0OQttLlFeaSQ1LfJqOvIKSIQbWl5p1JosjOcYtV2mvDrBj7OgjR7aXKC8Iot4mrB40nYY2xNP9Qy8ha10ArOkpYuURsRbsORMLLlA4eOHi%2FCZsPABQstDC5%2F26PDCViBaukzhgxYsORNLLlH4kEX4TFf4uOMnPvjBwlZ02UoLMC9A%2BPh0wZIzseQShU%2B7V2URPqMLH2%2F8LAZ%2Fcahos5WWaTmXIHzUCaoLlpyGJRcofIJ23rIIn%2FGFz%2FgpCcHCVnSBWdLSRQofcJzZaVWZ%2BFhV5g1W6vtWQp3d8fIxolT%2FOdoDmLpqzRZaOI0WLlHEtvuOFhE7uoj1x0%2BrCBa3kTZbudwiKnDGl0ERe9pQw0WIjojtFyhEvVlMuGs0Bi%2Bfr0%2F7qek11kZSJxhcD9I5va826VrJVFvtsOVGVrtqe3Ws8ozZs8fZ9INg64gtSW5OZ8pHB8lOo4uGFvfsKDmSEQEDQ0VO5ptnuvRHG8Z2Cjv72BxMbjzZn4PJK1njYEOMpvd8PDYHE7siSf20HGEKstrY6dI5mws0Ix6YsxGNosfmRkBbJWyx1Ic1Rhs%2FDiDWFpLAjbQ17uM7q3ALKAyMoN6g1jqpekSjOPCcnWX7SjcetLMUP7rE2s6C8weG3VmN%2BrmzdjaK6dMa2lmypvHjk6WdhVxbQ%2B%2BsRsOgc3b26Skma3BnN0H4aKoRprqzQDr80Dvb7g4yIqVvkCCKHwQXkNpxUpwGIXZcRc1Of0cGHF6ouOb9%2B8YT1zXznRgalWG9leBzlNDogpEGaK0%2FNNK09%2FoeCWlWXxb%2BoqIKH%2BI4IqoMYExKk4nETsuLt%2Bswx3BEJID6KZlEAirwCCy4Cvz21tslciweUy0cIuP7FSikqAziMXVubsqBMEsASEQJEl5L81B7O1CBtWy5UMkgLlQ6mnu%2F98zwD42sgdxDuzeqKivZQtT6RpYRFVLPWv0zgAMGu55XZHMBg5lo22AmHeR8TqPNNj7MNqlkpAHppmLH%2BL5dCmhIB8VGjHIQQYERpyNQQfnJ83N%2BaUZS%2BLiGXOn5JJjZYnCFT4WoLv1VwQXtQZscL8YctKnkVBrAHqmPP4KscQB18qkzJyMPO0yTXNs90DzT%2BF7%2Bnmzi%2FIr%2FBw%3D%3D), [редактирование](https://github.dev/web-ds-demographic/demographic_analyzer/blob/main/demographics.drawio) (нужно установить расширение Draw.io Integration - [инструкция](https://www.drawio.com/blog/edit-diagrams-with-github-dev)), [исходники](https://github.com/web-ds-demographic/demographic_analyzer/blob/main/demographics.drawio).

**Comment by st1gmat** [comment]
@sevryukov

**Comment by sevryukov** [comment]
@st1gmat посмотрел, спасибо. Уверен, что могут быть замечания, но лучше действовать и на практике улучшать.
