### ISSUE TITLE
Оффлайн встреча с двумя заказчиками

### ISSUE THREAD

**Issue by st1gmat** [web-ds-demographic/demographic_analyzer#3]
6 октября В.В.Захаров готов встретиться на обеде (в 13:00) в каб.408 и дать свои разъяснения по задаче

**Comment by DimaIbr** [comment]
Варианты методов решения задачи:
1) Авторегрессионные модели (ARMA, ARIMA, SARIMA и т.д.)
2) Камерные модели (из предоставленной статьи, но нужна адаптация)
3) NARX
