### ISSUE TITLE
Сбор информации по проекту, поиск открытых демографических данных

### ISSUE THREAD

**Issue by st1gmat** [web-ds-demographic/demographic_analyzer#4]

**Comment by st1gmat** [comment]
https://wopr.worldpop.org/

**Comment by st1gmat** [comment]
https://data.worldbank.org/indicator/SP.POP.TOTL

**Comment by DimaIbr** [comment]
https://rosstat.gov.ru/folder/12781

**Comment by st1gmat** [comment]
Статья 

[Modeldemon.pdf](https://github.com/web-ds-demographic/demographic_analyzer/files/12847920/Modeldemon.pdf)

**Comment by mouminaa** [comment]
https://inform-durablesolutions-idp.org/fr/library/donnees-demographiques-de-base/donnees-demographiques-de-base/

**Comment by st1gmat** [comment]
https://www.kaggle.com/datasets/muonneutrino/us-census-demographic-data

**Comment by st1gmat** [comment]
На данный момент всё что есть. Возможно, будет дополняться.
