### ISSUE TITLE
Подготовить вопросы к оффлайн встрече

### ISSUE THREAD

**Issue by st1gmat** [web-ds-demographic/demographic_analyzer#5]
Вопросы по технической части проекта

**Comment by Midiy** [comment]
* Инфраструктура:  
  ** Источник данных:  
    *** Есть ли какая-то внешняя БД, с которой надо работать?   
      **** Если есть - что за БД и какая у неё схема?  
  ** Ресурсы:  
    *** На какие мощности расчитывать?  

* Архитектура:  
  ** Есть ли какие-то архитектурные ожидания/ограничения?  
  ** Нужна ли авторизация?  
    ** Если да - будут ли разные пользовательские роли?  
  ** В каком формате нужно уметь выгружать данные?  

* Технологии:  
  ** Есть ли ограничения на языки/библиотеки/т.д.?  
  ** Под какой лицензией код?
